---
sudo: required
dist: bionic

language: c

addons:
  apt:
    packages:
    - python-docutils

before_install:
  - apt update
  - apt install debian-archive-keyring
  - apt install curl gnupg apt-transport-https
  - echo "deb https://packagecloud.io/varnishcache/varnish60lts/ubuntu/ bionic main \
    deb-src https://packagecloud.io/varnishcache/varnish60lts/ubuntu/ bionic main" > /etc/apt/sources.list.d/varnishcache_varnish60lts.list
  or:
  - curl -L https://packagecloud.io/varnishcache/varnish60lts/gpgkey | sudo apt-key add -
  and:
  - sudo apt update
  - apt install varnish varnish-dev

before_install(manual):
  - set -e
  - wget https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
  - tar -zxf master.tar.gz
  - pushd varnish-cache-master
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -sj32
  - sudo make install
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j4

compiler:
  - clang
  - gcc
